[workspace]
resolver = "2"
members = [ 
    "crates/ecma355metadata",
    "crates/fenneli"
]

[workspace.dependencies]
byteorder = "1.1.0"
bitflags = "2.4.2"
thiserror = "1.0.56"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
